### ISSUE TITLE
.registry url points to cran-to-git instead of my universe

### ISSUE THREAD

**Issue by pfuehrlich-pik** [r-universe/pfuehrlich-pik#1]
My packages are not found and I think it's because in .gitmodules the url points to cran-to-git although it should point to https://github.com/pfuehrlich-pik/universe . Can you help here @jeroen ? Thanks in advance, heard your talk at useR and now want to try r-universe!

**Comment by jeroen** [comment]
your registry file has the wrong name i think.

Op vr 16 jul. 2021 17:21 schreef pfuehrlich-pik ***@***.***>:

**Comment by pfuehrlich-pik** [comment]
That was it! In the python world it's always package.json (and not packages.json), so that's probably where that came from. Anyway, thanks a lot!
